# navbar
menu:
  Home: /
  Archives: /archives/
  Wikis: /wikis/
  About: /about/

# site icon
favicon: /favicon.ico

# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default

# comments
comments:
  post: true
  about: true

# article contents sidebar
sidebar: false

# Analytics
## Baidu Analytics
#baidu_analytics:
## Google Analytics
#google_analytics:

# Comments
## Duoshuo
#duoshuo_shortname:
## Disqus
#disqus_shortname:

# Social links
social:
  email: muxuapp@email.com
  stack-overflow:
  twitter:
  facebook:
  github:
  weibo:
  zhihu:
  rss: /atom.xml
